version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- win-x86-librw_d3d9-mss
- win-x86-librw_gl3_glfw-mss
- win-x86-librw_d3d9-oal
- win-x86-librw_gl3_glfw-oal
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  GLEW_VER: "2.1.0"
  GLFW_VER: "3.3.2"
  GLEW_BASE: glew-%GLEW_VER%
  GLFW_BASE: glfw-%GLFW_VER%.bin.WIN32
  GLEW_FILE: "%GLEW_BASE%-win32.zip"
  GLFW_FILE: "%GLFW_BASE%.zip"
  GLEW_URL: https://github.com/nigels-com/glew/releases/download/%GLEW_BASE%/%GLEW_FILE%
  GLFW_URL: https://github.com/glfw/glfw/releases/download/%GLFW_VER%/%GLFW_FILE%
install:
- IF [%PLATFORM%] == [win-x86-librw_gl3_glfw-mss] IF NOT EXIST %GLEW_FILE% appveyor DownloadFile %GLEW_URL% -FileName "%APPVEYOR_BUILD_FOLDER%/%GLEW_FILE%"
- IF [%PLATFORM%] == [win-x86-librw_gl3_glfw-mss] 7z x "%APPVEYOR_BUILD_FOLDER%/%GLEW_FILE%"
- IF [%PLATFORM%] == [win-x86-librw_gl3_glfw-mss] IF NOT EXIST %GLFW_FILE% appveyor DownloadFile %GLFW_URL% -FileName "%APPVEYOR_BUILD_FOLDER%/%GLFW_FILE%"
- IF [%PLATFORM%] == [win-x86-librw_gl3_glfw-mss] 7z x "%APPVEYOR_BUILD_FOLDER%/%GLFW_FILE%"
- cmd: >-
    git submodule update --init --recursive

    premake5 vs2019 --with-librw --glewdir=%APPVEYOR_BUILD_FOLDER%/%GLEW_BASE% --glfwdir=%APPVEYOR_BUILD_FOLDER%/%GLFW_BASE%

build:
  project: build/re3.sln
  verbosity: minimal
after_build:
- 7z a "re3_%configuration%_%platform%_%APPVEYOR_BUILD_VERSION%.zip" bin/%PLATFORM%/%CONFIGURATION%/re3.exe bin/%PLATFORM%/%CONFIGURATION%/re3.pdb
artifacts:
- path: "re3_%configuration%_%platform%_%APPVEYOR_BUILD_VERSION%.zip"
  name: re3
deploy:
- provider: BinTray
  username: shfil119
  api_key:
    secure: xWnYDfNWM87iPoBFbz6L1XAduxijJRWSpQLhMDOjznmzbMCsORtdx2tmWmFLTwf6
  subject: gtamodding
  repo: re3
  package: "%configuration%_%platform%"
  version: "%APPVEYOR_BUILD_VERSION%"
  artifact: re3
  publish: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: false

cache:
- "%GLEW_FILE%"
- "%GLFW_FILE%"
